project:
  type: website

website:
  title: "Wu Jindi"
  navbar:
    background: "#5B00AE"
    left:
      - href: Index.qmd
        text: Index
      - abouteme.qmd
      - homework.qmd
      - labs.qmd